### ISSUE TITLE
Comment for "How to print unicode text to a thermal printer using react native"

### ISSUE THREAD

**Issue by manhtai** [manhtai/manhtai.github.io#2]
Post link https://manhtai.github.io/posts/print-unicode-to-thermal-printer-using-react-native/.

**Comment by dmtri** [comment]
well done! 👏

**Comment by voanhtuan318** [comment]
const TCVN3codepage = new Buffer([0x1b, 0x74, 48]);
Where do you get it, I do as your guide but still can't print Vietnamese

**Comment by manhtai** [comment]
[0x1b, 0x74, n] is **ECS t n** POS command, you can check it here:

http://content.epson.de/fileadmin/content/files/RSD/downloads/escpos.pdf

n is from character code table, it depends on the printer, you have to check your printer for the code page.

**Comment by xeb10154** [comment]
Great article! 👏 I am also looking at the 'react-native-bluetooth-serial' library, but I want to know if this is only for Bluetooth? Does this work over the network (ethernet/WiFi)?

**Comment by manhtai** [comment]
Nah I think it's for bluetooth only, hence the name. You have to find elsewhere.

**Comment by soubinkittiphanh** [comment]
Can i use in flutter  if yes, how ? for Lao language

**Comment by manhtai** [comment]
> Can i use in flutter if yes, how ? for Lao language

Sorry this tutorial is for React Native only, you have to look elsewhere then.

**Comment by nvdangbk94** [comment]
const TCVN3message = iconv.encode(message, 'tcvn')
In here, you encode message with 'tcvn' not 'tcvn3' ? are they the same?

**Comment by manhtai** [comment]
> const TCVN3message = iconv.encode(message, 'tcvn')
> In here, you encode message with 'tcvn' not 'tcvn3' ? are they the same?

Yes, they would be the same.
